name: release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+' # Push events to matching [0-9]+.[0-9]+.[0-9]+, i.e. 1.0.0, 187.753.5

env:
  PROJECT_NAME: YouTubeStreamTemplates
  FILENAME: YouTubeStreamTemplates
  ARTIFACT_WIN: windows-artifact

jobs:
  build:
    if: github.event.base_ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Paste Client Id and Secret
        run: |
          sed -i 's/CLIENT_ID/${{ secrets.CLIENT_ID }}/g' YouTubeStreamTemplates/src/LiveStreaming/LiveStreamService.cs
          sed -i 's/CLIENT_SECRET/${{ secrets.CLIENT_SECRET }}/g' YouTubeStreamTemplates/src/LiveStreaming/LiveStreamService.cs
     
      - name: Set VERSION variable from tag
        run: echo "VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Install dependencies
        run: nuget restore
        
      - name: Build
        run: dotnet build --configuration Release /p:Version=${VERSION} --no-restore
        
      - name: Test
        run: dotnet test  --configuration Release /p:Version=${VERSION} --no-restore --no-build
        
      - name: Pack
        run: dotnet pack  --configuration Release /p:Version=${VERSION} --no-restore --no-build --output .
        
      - name: Push
        run: dotnet nuget push YouTubeStreamTemplates.${VERSION}.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source "https://nuget.pkg.github.com/TheSwerik/index.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
