name: releaseTogether

on:
  push:
    branches: [ main ]
#    tags:
#      - '[0-9]+.[0-9]+.[0-9]+' # Push events to matching [0-9]+.[0-9]+.[0-9]+, i.e. 1.0.0, 187.753.5

env:
  PROJECT_NAME: YouTubeStreamTemplatesCrossPlatform
  FILENAME: YouTubeStreamTemplates

jobs:
  release:
#    if: github.event.base_ref == 'refs/heads/main'
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/setup-msbuild@v1.0.2

      - name: Get the version
        id: version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Change Project Variables
        run: |
          (gc "${{ env.PROJECT_NAME }}\${{ env.PROJECT_NAME }}.csproj") -replace '<OutputType>Exe</OutputType>', '<OutputType>WinExe</OutputType>' | Out-File -encoding ASCII "${{ env.PROJECT_NAME }}\${{ env.PROJECT_NAME }}.csproj"
          (gc "${{ env.PROJECT_NAME }}\${{ env.PROJECT_NAME }}.csproj") -replace '<DisableWinExeOutputInference>true</DisableWinExeOutputInference>', '<DisableWinExeOutputInference>false</DisableWinExeOutputInference>' | Out-File -encoding ASCII "${{ env.PROJECT_NAME }}\${{ env.PROJECT_NAME }}.csproj"
          (gc "Inno Config.iss") -replace '"0.0.0"', '"${{ steps.version.outputs.VERSION }}"' | Out-File -encoding ASCII "Inno Config.iss"

      - name: Paste Client Id and Secret
        run: |
          (gc "YouTubeStreamTemplates\src\LiveStreaming\LiveStreamService.cs") -replace '"CLIENT_ID"', '"${{ secrets.CLIENT_ID }}"' | Out-File -encoding ASCII "YouTubeStreamTemplates\src\LiveStreaming\LiveStreamService.cs"
          (gc "YouTubeStreamTemplates\src\LiveStreaming\LiveStreamService.cs") -replace '"CLIENT_SECRET"', '"${{ secrets.CLIENT_SECRET }}"' | Out-File -encoding ASCII "YouTubeStreamTemplates\src\LiveStreaming\LiveStreamService.cs"

      - name: Get PFX-Cert
        run: |
          $bytes = [Convert]::FromBase64String("${{ secrets.BASE64_ENCODED_PFX }}")
          [IO.File]::WriteAllBytes('developer-cert.pfx', $bytes)
          Import-PfxCertificate -FilePath .\developer-cert.pfx -CertStoreLocation Cert:\CurrentUser\My -Password (ConvertTo-SecureString -String '${{ secrets.PFX_KEY }}' -AsPlainText -Force)

      - name: Publish 64bit
        run: msbuild /t:restore,publish -v:m /p:Configuration=Release /p:PublishProfile=PublisUnixSigned /p:PublishDir=..\Publish\bin\64bit -property:RuntimeIdentifiers=win-x64 -property:RuntimeIdentifier=win-x64

      - name: Clean obj
        run: get-childitem -Include obj -Recurse -force | Remove-Item -Force -Recurse

      - name: Publish 32bit
        run: msbuild /t:restore,publish  -v:m /p:Configuration=Release /p:PublishProfile=PublisUnixSigned /p:PublishDir=..\Publish\bin\32bit -property:RuntimeIdentifiers=win-x86 -property:RuntimeIdentifier=win-x86

      - name: Clean obj
        run: get-childitem -Include obj -Recurse -force | Remove-Item -Force -Recurse

      - name: Publish Linux
        run: msbuild /t:restore,publish  -v:m /p:Configuration=Release /p:PublishProfile=PublisUnixSigned /p:PublishDir=..\Publish\linux -property:RuntimeIdentifiers=linux-x64 -property:RuntimeIdentifier=linux-x64

      - name: Clean obj
        run: get-childitem -Include obj -Recurse -force | Remove-Item -Force -Recurse

      - name: Publish MacOS
        run: msbuild /t:restore,publish  -v:m /p:Configuration=Release /p:PublishProfile=PublisUnixSigned /p:PublishDir=..\Publish\mac -property:RuntimeIdentifiers=osx-x64 -property:RuntimeIdentifier=osx-x64

      - name: Create Windows Installer
        run: iscc "/ssigntool=`$qC:\Program Files (x86)\Windows Kits\10\bin\x64\signtool.exe`$q sign /f developer-cert.pfx /t http://timestamp.comodoca.com/authenticode /p ${{ secrets.PFX_KEY }} /fd sha256 $f" /qp "Inno Config.iss"

      #TODO create/copy Makefile
      - name: Zip Linux
        run: |
          New-Item -Path . -Name "Installer" -ItemType "directory"
          tar -C Publish/linux --exclude=osx -czf "Installer/${{ env.FILENAME }}.tar.gz" .

      - name: Zip MacOS
        run: 7z a "Installer/${{ env.FILENAME }}.zip" ./Publish/* -xr!linux

      - name: Release
        run: echo 'create release'
#        uses: softprops/action-gh-release@v1
#        with:
#          fail_on_unmatched_files: true
#          prerelease: ${{ startsWith(steps.version.outputs.VERSION, '0.') }}
#          draft: false
#          files: |
#            Installer/${{ env.FILENAME }}.exe
#            Installer/${{ env.FILENAME }}.zip
#            Installer/${{ env.FILENAME }}.tar.gz
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}