name: release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+' # Push events to matching [0-9]+.[0-9]+.[0-9]+, i.e. 1.0.0, 187.753.5

env:
  PROJECT_NAME: YouTubeStreamTemplates
  FILENAME: YouTubeStreamTemplates
  ARTIFACT_WIN: windows-artifact

jobs:
  release:
    if: github.event.base_ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
     
      - name: Set VERSION variable from tag
        run: echo "VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Install dependencies
        run: nuget restore
        
      - name: Build
        run: dotnet build --configuration Release /p:Version=${VERSION} --no-restore
        
      - name: Test
        run: dotnet test  --configuration Release /p:Version=${VERSION} --no-restore --no-build
        
      - name: Pack
        run: dotnet pack  --configuration Release /p:Version=${VERSION} --no-restore --no-build --output .
        
      - name: Push to GitHub
        run: dotnet nuget push YouTubeStreamTemplates.${VERSION}.nupkg --skip-duplicate --api-key ${{ secrets.GITHUB_TOKEN }} --source "https://nuget.pkg.github.com/TheSwerik/index.json"
          
      - name: Push to Nuget
        run: dotnet nuget push YouTubeStreamTemplates.${VERSION}.nupkg --skip-duplicate --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json